package py.gov.asuncion.turnero.all.view;

import java.util.List;
import javax.swing.JOptionPane;
import py.gov.asuncion.turnero.all.conexion.SocketConexion;
import py.gov.asuncion.turnero.all.data.dto.Dependencia;
import py.gov.asuncion.turnero.all.data.dto.Orden;
import py.gov.asuncion.turnero.all.data.jdbcRepository.DependenciaJdbcRepository;
import py.gov.asuncion.turnero.all.data.jdbcRepository.OrdenJdbcRepository;
import py.gov.asuncion.turnero.all.model.SocketDataSendModel;
import py.gov.asuncion.turnero.all.util.ProcesosUtil;

/**
 * * * @author cbaez 02
 */
public class LlamadorView extends javax.swing.JFrame {

    private Dependencia dependencia;
    private List<Dependencia> dependencias;

    Integer var01 = 0;
    Integer vNorden;
    String vValNum;
    String vLetra;

    String vNdep, vEstado;

    public LlamadorView() {
        initComponents();
        DependenciaJdbcRepository dependenciaJdbcRepository = new DependenciaJdbcRepository();
        dependencias = dependenciaJdbcRepository.getDependenciasByEstado(true);
        if (dependencias.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ocurrio Un error: No se encontraron Dependencias", "Atencion",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            for (Dependencia depe : dependencias) {
                this.cboDependencia.addItem(depe.getDescripcion());
            }
            JOptionPane.showMessageDialog(null, "Conectado", "Bienvenido", JOptionPane.INFORMATION_MESSAGE);
            this.setLocationRelativeTo(null);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        TexTicket = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        TexNvox = new javax.swing.JTextField();
        cboDependencia = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bookmark_1.png"))); // NOI18N
        jButton1.setText("Atendido");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        TexTicket.setBackground(new java.awt.Color(238, 238, 238));
        TexTicket.setFont(new java.awt.Font("Ubuntu Medium", 1, 48)); // NOI18N
        TexTicket.setToolTipText("");
        TexTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TexTicketActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("N° de Box:");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/list_5.png"))); // NOI18N
        jButton3.setText("Siguiente");
        jButton3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });

        TexNvox.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        TexNvox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TexNvoxActionPerformed(evt);
            }
        });

        cboDependencia.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cboDependencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboDependenciaMouseClicked(evt);
            }
        });
        cboDependencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboDependenciaActionPerformed(evt);
            }
        });
        cboDependencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboDependenciaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cboDependencia, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(TexTicket))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TexNvox, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TexNvox, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboDependencia, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TexTicket))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jButton1.setEnabled(false);
        jButton3.setEnabled(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TexTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TexTicketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TexTicketActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        obtenerDependencia();
        obtenerOrden();
    }//GEN-LAST:event_jButton3ActionPerformed

    public void obtenerOrden() {

        if (TexNvox.getText() == null || TexNvox.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe ingresar un Nro. de Box!",
                    "Atención", JOptionPane.INFORMATION_MESSAGE);
        } else {
            TexNvox.setEnabled(false);
            cboDependencia.setEnabled(false);
            OrdenJdbcRepository ordenJdbcRepository = new OrdenJdbcRepository();
            Integer idOrden = ordenJdbcRepository.getMinIdorden(dependencia.getIddependencia());
            Orden orden = ordenJdbcRepository.getByIdOrden(idOrden);
            if (orden != null) {
                vNorden = orden.getNOrden();
                vValNum = ProcesosUtil.valNumMenos10(vNorden);
                vLetra = orden.getAbec();
                vNdep = orden.getIdDependencia().toString();
                vEstado = "P";
                orden.setClienteIdCliente(Integer.parseInt(TexNvox.getText().trim().toString()));
                TexTicket.setText(vLetra + vValNum);

                ordenJdbcRepository.updateOrden(orden);

                SocketDataSendModel socketDataSendModel = new SocketDataSendModel();
                socketDataSendModel.setNroOrden(orden.getNOrden());
                socketDataSendModel.setNombreArchivoNroOrden(orden.getNOrden() + ".wav");

                socketDataSendModel.setLetra1(orden.getAbreDependencia().substring(0, 1));
                socketDataSendModel.setLetra2(orden.getAbreDependencia().substring(1));

                socketDataSendModel.setLetra3(orden.getAbec());
                socketDataSendModel.setNombreArchivoLetra(orden.getAbec().toLowerCase() + ".wav");
                if (orden.getAbec().equals("Ñ")) {
                    socketDataSendModel.setNombreArchivoLetra("ne.wav");
                }
                socketDataSendModel.setNroTerminal(orden.getClienteIdCliente());
                socketDataSendModel.setNombreArchivoNroTerminal(orden.getClienteIdCliente() + ".wav");
                socketDataSendModel.setDescripcionDependencia(dependencia.getDescripcion());
                socketDataSendModel.setNombreArchivoDescripcionDependencia(dependencia.getNombreArchivo());

                SocketConexion socketConexion = new SocketConexion();
                socketConexion.send(socketDataSendModel);
                jButton1.setEnabled(true);
                jButton3.setEnabled(false);
            } else {
                jButton1.setEnabled(false);
                jButton3.setEnabled(true);
                JOptionPane.showMessageDialog(null, "No Hay tickets",
                        "Atención", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }

    private void obtenerDependencia() {
        DependenciaJdbcRepository dependenciaJdbcRepository = new DependenciaJdbcRepository();
        dependencia = dependenciaJdbcRepository.getDependenciaByDescripcion(this.cboDependencia.getSelectedItem().toString());
        if (dependencia == null) {
            JOptionPane.showMessageDialog(null, "Ocurrio Un error: No se encontro Dependencia", "Atencion",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void TexNvoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TexNvoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TexNvoxActionPerformed

    private void cboDependenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboDependenciaMouseClicked
        obtenerDependencia();
    }//GEN-LAST:event_cboDependenciaMouseClicked

    private void cboDependenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboDependenciaActionPerformed

    }//GEN-LAST:event_cboDependenciaActionPerformed

    private void cboDependenciaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboDependenciaKeyPressed

    }//GEN-LAST:event_cboDependenciaKeyPressed

    private void jButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyPressed

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LlamadorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LlamadorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LlamadorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LlamadorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LlamadorView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TexNvox;
    private javax.swing.JTextField TexTicket;
    private javax.swing.JComboBox cboDependencia;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
