package py.gov.asuncion.turnero.all.vistas;

import javax.swing.JOptionPane;
import java.util.Date;
import javax.print.PrintService;
import javax.print.PrintServiceLookup;
import py.gov.asuncion.turnero.all.data.dto.Abecedario;
import py.gov.asuncion.turnero.all.data.dto.Dependencia;
import py.gov.asuncion.turnero.all.data.dto.Orden;
import py.gov.asuncion.turnero.all.data.dto.OrdenHistorico;
import py.gov.asuncion.turnero.all.data.dto.Param;
import py.gov.asuncion.turnero.all.data.jdbcRepository.AbecedarioJdbcRepository;
import py.gov.asuncion.turnero.all.data.jdbcRepository.DependenciaJdbcRepository;
import py.gov.asuncion.turnero.all.data.jdbcRepository.OrdenHistoricoJdbcRepository;
import py.gov.asuncion.turnero.all.data.jdbcRepository.OrdenJdbcRepository;
import py.gov.asuncion.turnero.all.data.jdbcRepository.ParamJdbcRepository;
import py.gov.asuncion.turnero.all.model.TicketModel;
import py.gov.asuncion.turnero.all.util.ConstantUtil;
import py.gov.asuncion.turnero.all.util.DateUtil;
import py.gov.asuncion.turnero.all.util.PrinterUtil;
import py.gov.asuncion.turnero.all.util.TicketPrintable;
import static py.gov.asuncion.turnero.all.vistas.Monitor.GRUPO_PATH;

/**
 * * @author cbaez
 */
public final class Ticket extends javax.swing.JFrame {

    public final static String GRUPO_ABCD = "ABCD";

    private Dependencia dependencia;
    private Orden orden;
    private TicketModel ticketModel;

    private Integer vIddep = 0;
    private String abreviaturaDependencia;
    private String vTPendiente;
    private String nombreImpresora;

    /**
     * * Creates new form cliente
     */
    public Ticket() {
        OrdenJdbcRepository ordenJdbcRepository = new OrdenJdbcRepository();
        Orden orden2 = ordenJdbcRepository.getOneOrdenFecha();
        if (orden2 != null) {
            System.out.println(orden2.toString());
            Date dateNow = new Date();
            if (!DateUtil.compararFechas(dateNow, orden2.getFecha())) {
                //SE INICIALIZA LA TABLA ORDEN 
                if (!ordenJdbcRepository.deleteAll()) {
                    JOptionPane.showMessageDialog(null, "Hubo problemas al borrar la tabla Orden", "Atención",
                            JOptionPane.INFORMATION_MESSAGE);
                }
            }
            initComponents();
            PrintService[] printServices = PrintServiceLookup.lookupPrintServices(null, null); //Obtenemos los servicios de impresion del sistema 
            for (PrintService impresora : printServices) { //Recorremos el array de servicios de impresion
                this.comboImpresoras.addItem(impresora.getName());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Hubo problemas para conectar con la base de datos", "Atención",
                    JOptionPane.INFORMATION_MESSAGE);
        }

    }

    /**
     * * This method is called from within the constructor to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        TextUltimoImpreso = new javax.swing.JTextField();
        TextPendFacturacion = new javax.swing.JTextField();
        TextPendGestion = new javax.swing.JTextField();
        TextPendPatentes = new javax.swing.JTextField();
        TextPendGrandes = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        TextPendInmuebles = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        comboImpresoras = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButton8.setBackground(new java.awt.Color(255, 153, 0));
        jButton8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("GESTION TRIBUTARIA");
        jButton8.setToolTipText("");
        jButton8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 153, 0));
        jButton5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("FACTURACION");
        jButton5.setToolTipText("");
        jButton5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(255, 153, 0));
        jButton7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("PATENTES");
        jButton7.setToolTipText("");
        jButton7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_tic.png"))); // NOI18N

        jLabel8.setForeground(new java.awt.Color(0, 153, 0));
        jLabel8.setText(" DIRECCION DE TIC's (TECNOLOGIA DE LA INFORMACION");

        jLabel4.setForeground(new java.awt.Color(0, 153, 0));
        jLabel4.setText("E INNOVACION TECNOLOGICA");

        jLabel6.setForeground(new java.awt.Color(0, 153, 0));
        jLabel6.setText(" DIRECCION GENERAL DE PLANIFICACION ");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_horizontal_2.png"))); // NOI18N
        jLabel5.setToolTipText("");
        jLabel5.setMaximumSize(new java.awt.Dimension(45, 70));
        jLabel5.setMinimumSize(new java.awt.Dimension(45, 70));
        jLabel5.setPreferredSize(new java.awt.Dimension(45, 70));

        jButton9.setBackground(new java.awt.Color(255, 153, 0));
        jButton9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("GRANDES CONTRIBUYENTES");
        jButton9.setToolTipText("");
        jButton9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(255, 153, 0));
        jButton10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("M.E. ATENCION AL CONTRIB.");
        jButton10.setToolTipText("");
        jButton10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        TextUltimoImpreso.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        TextUltimoImpreso.setEnabled(false);
        TextUltimoImpreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextUltimoImpresoActionPerformed(evt);
            }
        });

        TextPendFacturacion.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        TextPendFacturacion.setEnabled(false);
        TextPendFacturacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextPendFacturacionActionPerformed(evt);
            }
        });

        TextPendGestion.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        TextPendGestion.setEnabled(false);
        TextPendGestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextPendGestionActionPerformed(evt);
            }
        });

        TextPendPatentes.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        TextPendPatentes.setEnabled(false);
        TextPendPatentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextPendPatentesActionPerformed(evt);
            }
        });

        TextPendGrandes.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        TextPendGrandes.setEnabled(false);
        TextPendGrandes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextPendGrandesActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 0));
        jLabel11.setText("  PENDIENTES");

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 153, 0));
        jLabel15.setText("ULTIMO IMPRESO");

        TextPendInmuebles.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        TextPendInmuebles.setEnabled(false);
        TextPendInmuebles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextPendInmueblesActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 153, 0));
        jLabel12.setText("DEPENDENCIAS");

        comboImpresoras.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboImpresorasItemStateChanged(evt);
            }
        });
        comboImpresoras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboImpresorasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jLabel4))
                            .addComponent(jLabel6)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(79, 79, 79)
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(91, 91, 91)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TextPendGrandes)
                                .addComponent(TextPendPatentes)
                                .addComponent(TextPendFacturacion)
                                .addComponent(TextPendInmuebles)
                                .addComponent(TextPendGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(TextUltimoImpreso, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(473, 473, 473))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(260, 260, 260))))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboImpresoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addComponent(comboImpresoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextPendGestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextPendFacturacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(TextUltimoImpreso, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextPendPatentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextPendGrandes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(TextPendInmuebles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 36, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {TextPendFacturacion, TextPendGestion, TextPendGrandes, TextPendPatentes});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1004, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void generaNumero() {
        //Obtiene la descripcion de la Dependencia para el ticket
        if (obtenerDependencia()) {
            if (obtenerSiguienteOrdenByDependenciaId(dependencia.getIddependencia())) {
                armarTicket();
                if (!imprimirTicket()) {
                    JOptionPane.showMessageDialog(null, "Hubo problemas con la Impresión del Ticket", "Atención",
                            JOptionPane.INFORMATION_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Hubo problemas con la seleccion del Contador", "Atención",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Hubo problemas con la seleccion de Dependencias", "Atención",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private boolean obtenerDependencia() {
        DependenciaJdbcRepository dependenciaJdbcRepository = new DependenciaJdbcRepository();
        dependencia = dependenciaJdbcRepository.getDependenciaById(vIddep);
        if (dependencia == null) {
            return false;
        }
        return true;
    }

    private boolean obtenerSiguienteOrdenByDependenciaId(Integer idDependencia) {
        OrdenJdbcRepository ordenJdbcRepository = new OrdenJdbcRepository();
        Integer nroOrdenActual = ordenJdbcRepository.getMaxIdordenByDependenciaId(dependencia.getIddependencia());
        orden = ordenJdbcRepository.getByIdOrden(nroOrdenActual);
        if (orden == null) {
            orden = new Orden();
            orden.setNOrden(0);
            orden.setNLetra(1);
            orden.setAbec("A");
        }

        orden.setNOrden(orden.getNOrden() + 1);

        if (orden.getNOrden() > 100) {
            ParamJdbcRepository paramJdbcRepository = new ParamJdbcRepository();
            Param param = paramJdbcRepository.getParamByGrupoAndCodigo(GRUPO_ABCD, "MAXLETRAS");
            if (param != null) {
                System.out.println("VALOR: " + param.getValor());
                Integer maxLetrasLlamar = Integer.valueOf(param.getValor());
                //Buscar letra actual (n_letra + 1)
                AbecedarioJdbcRepository abecedarioJdbcRepository = new AbecedarioJdbcRepository();
                Integer idLetra = orden.getNLetra() + 1;
                if (idLetra > maxLetrasLlamar) {
                    idLetra = 1;
                }
                Abecedario abecedario = abecedarioJdbcRepository.getAbecedarioByIdAbecedario(idLetra);
                orden.setNOrden(1);
                orden.setNLetra(abecedario.getIdabc());
                orden.setAbec(abecedario.getLetra());
            } else {
                JOptionPane.showMessageDialog(null, "Hubo problemas para obtener parametro MaxLetras", "Atención",
                        JOptionPane.INFORMATION_MESSAGE);
                return false;
            }

        }

        orden.setIdOrden(ordenJdbcRepository.getMaxIdorden() + 1);
        orden.setClienteIdCliente(0);
        orden.setIdDependencia(dependencia.getIddependencia());
        orden.setEstado("P");
        orden.setFecha(new Date());
        orden.setAbreDependencia(abreviaturaDependencia);
        if (!ordenJdbcRepository.insertOrden(orden)) {
            JOptionPane.showMessageDialog(null, "Hubo al insertar el siguiente Turno", "Atención NO IMPRIMA MAS NUMEROS LLAME AL TECNICO CEL. 0961-376440",
                    JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        return true;
    }

    private void armarTicket() {
        ticketModel = new TicketModel();
        ticketModel.setDependenciaNombre(dependencia.getDescripcion());
        ticketModel.setLetra(orden.getAbreDependencia() + orden.getAbec());
        ticketModel.setNumero(orden.getNOrden());
    }

    private boolean imprimirTicket() {
        System.out.println("Ticket: " + ticketModel.toString());
//        TicketPrintable ticketPrintable = new TicketPrintable(ticketModel);
//        if (PrinterUtil.print(ticketPrintable, nombreImpresora)) {
//            OrdenHistorico ordenHistorico = new OrdenHistorico();
//            ordenHistorico.setClienteIdCliente(0);
//            ordenHistorico.setNOrden(ticketModel.getNumero());
//            ordenHistorico.setAbec(ticketModel.getLetra());
//            ordenHistorico.setIdDependencia(dependencia.getIddependencia());
//            ordenHistorico.setFecha(new Date());
//            OrdenHistoricoJdbcRepository ordenHistoricoJdbcRepository = new OrdenHistoricoJdbcRepository();
//            if (!ordenHistoricoJdbcRepository.insertOrdenHistorico(ordenHistorico)) {
//                JOptionPane.showMessageDialog(null, "Hubo al insertar el siguiente Turno Historico", "Atención NO IMPRIMA MAS NUMEROS LLAME AL TECNICO CEL. 0961-376440",
//                        JOptionPane.INFORMATION_MESSAGE);
//                return false;
//            }
//        } else {
//            JOptionPane.showMessageDialog(null, "Hubo al imprimir el Ticket", "Atención NO IMPRIMA MAS NUMEROS LLAME AL TECNICO CEL. 0961-376440",
//                    JOptionPane.INFORMATION_MESSAGE);
//            return false;
//        }
        return true;
    }


    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        //facturacion
        abreviaturaDependencia = ConstantUtil.FACTURACION;
        vIddep = 2;
        generaNumero();
        TextPendFacturacion.setText(vTPendiente);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        //patentes
        abreviaturaDependencia = ConstantUtil.PATENTES;
        vIddep = 4;
        generaNumero();
        TextPendPatentes.setText(vTPendiente);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        //gestion
        abreviaturaDependencia = ConstantUtil.GESTION_TRIBUTARIA;
        vIddep = 3;
        generaNumero();
        TextPendGestion.setText(vTPendiente);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        //GRANDES
        abreviaturaDependencia = ConstantUtil.GRANDES_CONTRIBUYENTES;
        vIddep = 5;
        generaNumero();
        TextPendGrandes.setText(vTPendiente);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        //ATENCION
        abreviaturaDependencia = ConstantUtil.ATENCION_AL_CONTRIBUYUNTES;
        vIddep = 7;
        generaNumero();
        TextPendInmuebles.setText(vTPendiente);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void TextUltimoImpresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextUltimoImpresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextUltimoImpresoActionPerformed

    private void TextPendFacturacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextPendFacturacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextPendFacturacionActionPerformed

    private void TextPendGestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextPendGestionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextPendGestionActionPerformed

    private void TextPendPatentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextPendPatentesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextPendPatentesActionPerformed

    private void TextPendGrandesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextPendGrandesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextPendGrandesActionPerformed

    private void TextPendInmueblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextPendInmueblesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextPendInmueblesActionPerformed

    private void comboImpresorasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboImpresorasMouseClicked

    }//GEN-LAST:event_comboImpresorasMouseClicked

    private void comboImpresorasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboImpresorasItemStateChanged
        nombreImpresora = this.comboImpresoras.getSelectedItem().toString();
    }//GEN-LAST:event_comboImpresorasItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ticket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextPendFacturacion;
    private javax.swing.JTextField TextPendGestion;
    private javax.swing.JTextField TextPendGrandes;
    private javax.swing.JTextField TextPendInmuebles;
    private javax.swing.JTextField TextPendPatentes;
    private javax.swing.JTextField TextUltimoImpreso;
    private javax.swing.JComboBox<String> comboImpresoras;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
